server:  port: 9090
kafka:
  topic: si.topic
  newTopic: si.new.topic
  messageKey: si.key
spring:
  activemq:
    in-memory: true
    pool:
      enabled: false
    broker-url:  tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: siTestGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:file:~/Kafka-MQ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
logging:
    level:
      root: INFO
      org.springframework.integration.channel: DEBUG
    


